### ISSUE TITLE
Buying the contributors a coffee!

### ISSUE THREAD

**Issue by PeterCloet** [add-ons/plugin.video.goplay#5]
Will you be adding the option to buy you, Michaël and Dag a coffee?
This plugin is so well received/used in our household, that I would really like to show my appreciation.

**Comment by mediaminister** [comment]
No, thanks a lot for the appreciation, but I do this completely for free in my spare time. I guess Michaël and Dag have said goodbye to Kodi in exchange for Android TV.

All this plugin needs is more Kodi users and additional contributors to keep it going.
