### ISSUE TITLE
Tafel Van Gert Season 5 does not play

### ISSUE THREAD

**Issue by trick72** [add-ons/plugin.video.goplay#6]
Many thanks for building this new GoPlay plugin.
Most programs play fine, but Season 5 of "De Tafel Van Gert" does not. Only "Aflevering 1" is there, while there are already more. So it seems new episodes are not added to the list. When I try to play "Aflevering 1 " I got an error message "see log for details".
Does anyone else experience this too? I'm on latest kodi, on a raspberry PI 5 .
Thanks

**Comment by mediaminister** [comment]
This should be fixed in the master branch now.
Can you confirm if the fix works?
Test package: [plugin.video.goplay-0.5.0-fixcache.zip](https://github.com/user-attachments/files/17042025/plugin.video.goplay-0.5.0-fixcache.zip)

**Comment by trick72** [comment]
Oh wow, yes. Many thanks. The update fixed it, I see 2 episodes now and they play fine!
So nice!!!
